apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "httpbin-deploy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "httpbin-deploy.labels" . | nindent 4 }}


