apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpbin-deploy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "httpbin-deploy.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: http
  selector:
    {{- include "httpbin-deploy.selectorLabels" . | nindent 4 }}
