apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "httpbin-deploy.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ .Values.hostname }}
  gateways:
  - httpbin-gateway
  http:
  - match:
    - uri:
        prefix: /status
    - uri:
        prefix: /delay
    route:
    - destination:
        port:
          number: 8000
        host: {{ include "httpbin-deploy.fullname" . }}