apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-uat
  namespace: openshift-gitops
  labels:
    app-type: httpbin-uat
spec:
  destination:
    namespace: lbg-ocp-meshtest-309-lab
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/
    repoURL: https://github.com/glaceroy/httpbin-deploy.git
    targetRevision: HEAD
    helm:
      version: v3
      valueFiles:
        - values-uat.yaml
  info:
    - name: 'Purpose'
      value: 'Application to test istio use cases'
  syncPolicy:
    automated: {}
