apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-deploy
  namespace: openshift-gitops
  labels:
    app-type: httpbin-deploy
spec:
  destination:
    namespace: lbg-ocp-engineering-100-lab
    server: https://kubernetes.default.svc
  project: bookinfo-project-dev
  source:
    path: development/helm-config/
    repoURL: https://github.com/glaceroy/bookinfo
    targetRevision: HEAD
    helm:
      version: v3
      valuesFile:
        - development/helm-config/values.yaml
  info:
    - name: 'Purpose'
      value: 'Application to test istio use cases'
  syncPolicy:
    automated: {}
