namespace: lbg-ocp-engineering-100-lab

replicaCount: 1
image:
  repository: utility.cloud.lab:8443/httpbin/go-httpbin
  pullPolicy: IfNotPresent
  tag: v2.15.0

service:
  port: 8000
  targetport: 8080

route:
  hostname: httpbin-smesh.apps.ocp.cloud.lab
  service: ig001

podAnnotations:
  sidecar.istio.io/inject: "true"

podLabels:
  app: httpbin
  version: v1

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
